# Generated by Django 4.2.3 on 2023-07-21 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('facultad', models.CharField(choices=[('agropecuaria', 'Agropecuaria y de Recursos Naturales Renovables'), ('educación', 'Educación, el Arte y la Comunicación'), ('energía', 'Energía, las Industrias y los Recursos Naturales no Renovables'), ('jurídica', 'Jurídica, Social y Administrativa'), ('salud', 'Salud Humana'), ('distancia', 'Unidad de Educación a Distancia y en Línea')], max_length=30)),
                ('inicio_periodo', models.DateField()),
                ('final_periodo', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('carrera', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sistema_tutorias.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('ciclo', models.CharField(max_length=20)),
                ('paralelo', models.CharField(max_length=5)),
                ('carrera', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sistema_tutorias.carrera')),
                ('docente', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sistema_tutorias.docente')),
            ],
        ),
    ]
