# Generated by Django 4.2.3 on 2023-07-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20)),
                ('cargo', models.CharField(choices=[('decano', 'Decano'), ('docente', 'Docente'), ('estudiante', 'Estudiante'), ('director', 'Director')], max_length=20)),
            ],
        ),
    ]
