# Generated by Django 4.2.3 on 2023-07-21 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_tutorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('carrera', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sistema_tutorias.carrera')),
            ],
        ),
        migrations.RemoveField(
            model_name='registroactividades',
            name='asignatura',
        ),
        migrations.RemoveField(
            model_name='registroactividades',
            name='lista',
        ),
        migrations.RemoveField(
            model_name='tutoria',
            name='asignatura',
        ),
        migrations.RemoveField(
            model_name='tutoria',
            name='docente',
        ),
        migrations.DeleteModel(
            name='Informe',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='RegistroActividades',
        ),
        migrations.DeleteModel(
            name='Tutoria',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='docente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sistema_tutorias.docente'),
        ),
    ]
