# Generated by Django 4.2.3 on 2023-07-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_tutorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('facultad', models.CharField(max_length=20)),
                ('inicio_periodo', models.DateField()),
                ('final_periodo', models.DateField()),
            ],
        ),
    ]
