# Generated by Django 4.2.3 on 2023-08-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_tutorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='correo',
            field=models.EmailField(default=2, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='horario',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
