# Generated by Django 4.2.3 on 2023-07-21 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_tutorias', '0002_docente_delete_informe_delete_registroactividades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='asignatura',
            field=models.ManyToManyField(limit_choices_to={'carrera': models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sistema_tutorias.carrera')}, to='sistema_tutorias.asignatura'),
        ),
    ]
