# Generated by Django 4.2.3 on 2023-07-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_tutorias', '0002_carrera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('ciclo', models.CharField(max_length=20)),
                ('paralelo', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='carrera',
            name='facultad',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
    ]
