# Generated by Django 4.2.3 on 2023-07-21 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_tutorias', '0003_alter_docente_asignatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='asignatura',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='docente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sistema_tutorias.docente'),
        ),
    ]
