# Generated by Django 4.2.3 on 2023-07-14 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_tutorias', '0003_asignatura_alter_carrera_facultad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='carrera',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sistema_tutorias.carrera'),
        ),
    ]
