# Generated by Django 4.2.3 on 2023-07-21 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_tutorias', '0005_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='carrera',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sistema_tutorias.carrera'),
        ),
    ]
