# Generated by Django 4.2.3 on 2023-07-21 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_tutorias', '0006_alter_user_carrera'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
